### ISSUE TITLE
uninitialized constant Grape::Validations::SingleOptionValidator

### ISSUE THREAD

**Issue by 3dd13** [monterail/grape-kaminari#20]
I got this error with latest Grape master branch:

    NameError: uninitialized constant Grape::Validations::SingleOptionValidator
    /Users/eddielau/.rvm/gems/ruby-2.1.5/bundler/gems/grape-kaminari-5478f299fc53/lib/grape/kaminari/max_value_validator.rb:3:in `<module:Kaminari>'

checked the SingleOptionValidator has already gone.
refer to https://github.com/intridea/grape/pull/754

**Comment by Ostrzy** [comment]
Fixed in https://github.com/monterail/grape-kaminari/pull/21
