### ISSUE TITLE
How about use Kaminari `limit_value` for `X-Per-Page`?

### ISSUE THREAD

**Issue by calfzhou** [monterail/grape-kaminari#23]
from the [source code](https://github.com/monterail/grape-kaminari/blob/80f7d66196a58b0d992265122541110f171ef7d0/lib/grape/kaminari.rb#L14) i see that now we return `X-Per-Page` with data `params[:per_page].to_s`, how about use Kaminari's `limit_value` instead?
```ruby
header "X-Per-Page",    data.limit_value.to_s
```

**Comment by teamon** [comment]
Is there any real difference? (Some edge cases maybe?)

**Comment by calfzhou** [comment]
when input `per_page` is not provided, `params[:per_page]` is nil, but `limit_value` is the actual value used by kaminari.

**Comment by teamon** [comment]
Yep, I saw the explanation in PR. Merged already, I just need to release a new version. Thanks!
