### ISSUE TITLE
Kaminari cache

### ISSUE THREAD

**Issue by jimlester** [monterail/grape-kaminari#27]
I'm researching the best way to cache a paginated collection. Do you think it makes sense to integrate caching into grape-kaminari similar to the kaminari-cache implementation?

Thank you for your help.

**Comment by teamon** [comment]
Have you seen https://github.com/monterail/grape-rails-cache/? :)

**Comment by teamon** [comment]
@jimlester Closing this for now. If you have any more comments please add a comment.
