### ISSUE TITLE
Collections

### ISSUE THREAD

**Issue by kris** [monterail/grape-kaminari#28]
There are assumptions made in this that you'll be doing `scope.page(page).per(count)`, but that isn't always the case. For example, paginating a `Searchkick::Results` object. Have you thought about removing that dependency and allowing for passing a generic collection that responds with the needed attributes?

**Comment by teamon** [comment]
This gem is a tight integration with kaminari, hence the assumptions.

At the same time, there is an example in the README how to paginate generic array:

```
    get do
      things = ['a', 'standard', 'array', 'of', 'things', '...']

      # Use `Kaminari.paginate_array` method to convert the array
      # into an object that can be passed to `paginate` helper.
      paginate(Kaminari.paginate_array(things))
    end
```

Does this solve your problem?

**Comment by teamon** [comment]
@kris Closing this for now. Please let me know if you have any more comments, I'm willing to reopen this issue anytime.
