### ISSUE TITLE
X-Per-Page not included when default page size is used

### ISSUE THREAD

**Issue by bandtank** [monterail/grape-kaminari#29]
When I don't include per_page in the request, the header isn't returned. When I do include it, the header is returned as expected. See below:

![screen shot 2015-08-07 at 2 29 33 pm](https://cloud.githubusercontent.com/assets/1170415/9145364/ef18edd0-3d10-11e5-94f4-ad04990dd699.png)
![screen shot 2015-08-07 at 2 29 58 pm](https://cloud.githubusercontent.com/assets/1170415/9145365/ef1adfd2-3d10-11e5-8640-bd6f75794541.png)

Also, the default page size in the gem is 10, but I get 25 when I don't send a page size. Where else could this be configured? I know it's possible to override the default as follows:

`paginate per_page: 20, max_per_page: 30, offset: 5`

However, I haven't written that anywhere, so I'm not sure why the default isn't 10. Any help would be greatly appreciated.

**Comment by bandtank** [comment]
@teamon if you could point me in the right direction, i'll do all of the work if any needs to be done to fix this. i think the header should be returned all the time regardless of if it's passed in or not.

**Comment by teamon** [comment]
@bandtank please take a look at this gist: https://gist.github.com/teamon/f87f9a96603018c9568c

It seems to be working fine. Please ensure you are using `v0.18` of grape-kaminari.

**Comment by bandtank** [comment]
@teamon That was the issue. Thank you. I didn't realize a new version had been released.
